spring:
  application:
    name: "rating_service"
  data:
    mongodb:
      uri: mongodb+srv://sdarnadeem:password%40123@cluster0.1aeyori.mongodb.net/?retryWrites=true&w=majority
      database: custer0
server:
  port: 3002
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9999/eureka
