server:
  port: 3003
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sdarnadeem/spring-boot-microservices
          clone-on-start: true
